name: New Editor Request
description: Request access to issues in this github repository
title: "[New Editor]: Add Editor <github user id>"
labels: ["NewEditor"]

body:
  - type: input
    id: UserId
    attributes:
      label: "Github User name"
    validations:
      required: true
  - type: input
    id: Name
    attributes:
      label: "Name"
    validations:
      required: true
  - type: input
    id: institution
    attributes:
      label: "Institution"
    validations:
      required: true
    
    
